<?php

/**
 * Implementation of hook_page_build
 */
function uservoice_page_build(&$page) {
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return FALSE;
  }

  $config = \Drupal::config('uservoice.settings');

  if (!$config->get('api_key')) {
    drupal_set_message(t('UserVoice setup is not complete. Go to !configureLink and add your API Key.', array('!configureLink' => Drupal::l('the settings page', 'admin/config/user-interface/uservoice'))), 'error');
    return;
  }

  $uservoice_settings = array(
    'api_key'                  => $config->get('api_key'),
    'accent_color'             => $config->get('accent_color'),
    'trigger_color'            => $config->get('trigger_color'),
    'trigger_background_color' => $config->get('trigger_background_color'),
    'trigger_style'            => $config->get('trigger_style'),
    'trigger_position'         => $config->get('trigger_position'),
    'mode'                     => $config->get('mode'),
    'locale'                   => $config->get('locale'),
  );
  $page['#attached']['library'][] = 'uservoice/uservoice';
  $page['#attached']['js'][] = array(
    'type' => 'setting',
    'data' => array('UserVoice' => $uservoice_settings),
  );

}
